version: '3.1'
services:
  data_generator:
    image: waitingforcode/data-generator-blogging-platform:0.3-beta
    volumes:
      - /tmp/dedp/ch05/02-decorator/01-wrapper-sql/input/:/home/data_generator_user/data_generator_output
      - ./generation_configuration_json.yaml:/home/data_generator_user/generation_configuration_json.yaml
    entrypoint:
      - python3
      - /home/data_generator_user/data_generator/generate_dataset.py
      - --config_file
      - /home/data_generator_user/generation_configuration_json.yaml

