dataset:
  rows: 50
  composition_percentage:
    duplicates: 0
    missing_fields: 0
    unprocessable_rows: 0
data_blocker:
  type: 'no'
entity:
  type: visit
  configuration:
    start_time: '2023-12-24T00:00:00Z'
generator:
  type: one-shot
writer:
  type: json
  configuration:
    output_path: '/home/data_generator_user/data_generator_output/input'
    clean_path: true
