version: '3.1'
services:
  postgresql:
    image: postgres:11
    container_name: dedp_ch06_01_sequencer_02
    environment:
      - POSTGRES_USER=dedp_test
      - POSTGRES_PASSWORD=dedp_test
      - POSTGRES_DB=dedp
    ports:
        - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - /tmp/dedp/ch06/01-sequence/02-isolated-sequencer-external-trigger/input-internal:/data_to_load
